[package]
name = "textile"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "textile"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
rustextile = "1"
reqwest = { version = "0.11.16", default-features = false, features = ["rustls-tls"] }